export const actionTypes = {
    UPDATE_AGE: 'UPDATE_AGE',
    UPDATE_DIRECTIONAL_STATEMENTS: 'UPDATE_DIRECTIONAL_STATEMENTS',
    UPDATE_FOOD_GROUPS: 'UPDATE_FOOD_GROUPS',
    UPDATE_FOODS: 'UPDATE_FOODS',
    UPDATE_GENDER: 'UPDATE_GENDER',
    UPDATE_SERVINGS_PER_DAY: 'UPDATE_SERVINGS_PER_DAY'
};
